### ISSUE TITLE
php 5.6 version tag

### ISSUE THREAD

**Issue by bryanestrito** [laradock/workspace#8]
Can you add a tag for php 5.6 version? so that we can easily switch on the version on laradock for the workspace.

**Comment by Mahmoudz** [comment]
@bryanestrito I'd like to support 5.6 in the workspace container. However, I don't think adding this tag will help! 

in order to support 5.6 in the workspace we need the following:
1. make another dockerfile like this https://github.com/laradock/workspace/blob/master/Dockerfile with 5.6 support.
2. make another docker file on laradock workspace https://github.com/laradock/laradock/blob/master/workspace/Dockerfile that supports 5.6
3. then make a tag that build from each file.
4. add docs explaining how to switch by updating the docker-compose file

The main problem will be is whenever doing any changes on the first dockerfile (7.0) we need to add it also on the other file (5.6).

Let me know your opinion.

**Comment by duckoder** [comment]
@Mahmoudz I think we can have only the base PHP packages installation instructions in workspace image. With this, we can handle 5.6 and 7.0 easily.
